### ISSUE TITLE
requireResidentKey Android 7 bug

### ISSUE THREAD

**Issue by mahnunchik** [MasterKale/SimpleWebAuthn#47] opened 2020-08-07 10:49 UTC
Hi,

I was trying to catch the bug for a week: Android 7.0 requires `authenticatorSelection.requireResidentKey` to be set to `false` to works without error:

> An unknown error occurred while talking to credential manager

Yep, it is default value https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/authenticatorSelection but attestation doesn't work without it.

![photo_2020-08-07_12-47-26](https://user-images.githubusercontent.com/780935/89638477-2e3dd480-d8ac-11ea-87a1-07bc49037b82.jpg)

I think the library may set `authenticatorSelection.requireResidentKey` to default value `false`.

**Comment by MasterKale** [comment] 2020-08-07 14:44
Huh, so Android 7 won't support attestations unless that optional value is explicitly set in attestation options? I don't see an issue with explicitly initializing that value in the library, might as well aim for as much device support as possible.

Can I know what device and specific OS variant you're testing on (stock Android, etc...)? I don't have anything that old to test with anymore so I can't reproduce this myself but I'm still curious.

**Comment by MasterKale** [comment] 2020-08-10 05:13
@mahnunchik I've got PR #48 out that should fix this. Are you comfortable building this package from that branch and testing it with Android 7 to see if it fixes this issue?

**Comment by mahnunchik** [comment] 2020-08-10 10:12
Hi @MasterKale it is the strangest error I have ever seen.

It seems it happens on Android 7 devices when you **never** use FIDO auth with any value in `requireResidentKey` or `userVerification`.

If you use first time FIDO auth on **any** website with `requireResidentKey` or `userVerification` then **FIDO** is fixed for future usage.

I've tested on the following devices:

* Huawei MediaPad M3 Lite 32Gb (CPN-L09) Android 7.0
* Redmi Note 4 MIUI Global 11.0.2 Android 7.0
* Wileyfox Swift 2 Android 7.0

Preposed PR should fix this issue but I don't have more Android 7.0 devices with **not fixed** FIDO auth to test it 😢

**Comment by MasterKale** [comment] 2020-08-12 05:44
That's unfortunate that it seems to be a one-time initialization thing...who knew what Google was thinking back then 🤷‍♂️ 

Nonetheless I've merged in that update with an explicit return value for `authenticatorSelection` that will hopefully address this going forward. This is available in **@simplewebauthn/server@0.8.2**.

Thank you for reporting this :v:

**Closed by MasterKale** 2020-08-12 05:44 UTC
Labels: package:server
