### ISSUE TITLE
Typescript types not working with `moduleResolution`: `nodenext`

### ISSUE THREAD

**Issue by hanssonduck** [MasterKale/SimpleWebAuthn#394] opened 2023-06-15 23:34 UTC
## Describe the issue
No types are recognized when importing any functions from either the server or client packages when `moduleResolution` is set to `nodenext` in `tsconfig.json`. Installing the separate types package does not solve the issue.

## Reproduction Steps

1. Create new typescript project
2. Set `moduleResolution` to `nodenext`
3. Install server and browser packages
4. Import any function and see no types

## Expected behavior

The types should be recognized as expected with this setting.

## Dependencies

- **Typescript:** 5.1.3
- **VSCode:** 1.79.2

### SimpleWebAuthn Libraries

Using the latest version of both packages.

## Additional context

Not sure why this is happening, tried looking into it but couldn't figure it out. 
Some info of the setting: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#esm-nodejs

**Comment by MasterKale** [comment] 2023-06-20 21:20
I'm pretty sure this is an ESM environment issue. Right now only CommonJS (read: Node) runtimes are officially supported by @simplewebauthn/server.

That said #338 has been tracking my efforts to add support for use of SimpleWebAuthn in ESM environments. There's no ETA right now as I work on that particular problem when I have time.

**Comment by hanssonduck** [comment] 2023-06-20 23:02
> I'm pretty sure this is an ESM environment issue. Right now only CommonJS (read: Node) runtimes are officially supported by @simplewebauthn/server.
> 
> That said #338 has been tracking my efforts to add support for use of SimpleWebAuthn in ESM environments. There's no ETA right now as I work on that particular problem when I have time.

Understood! 
The server package does work in edge environments like Cloudflare Workers. Probably due to the new Node compatibility mode https://blog.cloudflare.com/workers-node-js-asynclocalstorage. 
Reverted `moduleResolution`: `nodenext` until the ESM support has fully landed.
Feel free to close this in favour of #338.

**Comment by MasterKale** [comment] 2023-06-20 23:24
As acknowledged, closing as a dupe of #338 ✌️

**Closed by MasterKale** 2023-06-20 23:24 UTC
