### ISSUE TITLE
startAuthentication step does not complete

### ISSUE THREAD

**Issue by renchris** [MasterKale/SimpleWebAuthn#437] opened 2023-09-17 01:47 UTC
### startAuthentication does not complete

1. After entering in the email of the registered passkey and upon clicking submit on my web page, I invoke the startAuthentication function. My browser then asks to "choose a passkey".

<img width="751" alt="image" src="https://github.com/MasterKale/SimpleWebAuthn/assets/57972348/a82c1c4b-a52f-4e05-8e39-f8b922f99d6b">

 2. Upon clicking the respective passkey, the browser then asks me to verify which I do with my biometric password.

<img width="1004" alt="image" src="https://github.com/MasterKale/SimpleWebAuthn/assets/57972348/893619db-5b7a-4cc6-9389-7987aa0f589b">

3. I now expect this login process to be complete, however, now it asks me to "Use your passkey" with an alternative device or USB, which I do not have nor set up during my register process. I expect this is not expected behavior as I am now stuck in the log in process.

<img width="762" alt="image" src="https://github.com/MasterKale/SimpleWebAuthn/assets/57972348/34bd704c-c15e-4626-b1cc-77e699c8ee94">

Would I please get assistance of how to invoke startAuthentication with expected behaviour?

## Expected behavior

I expect now the startAuthentication function to correctly pass without any more user prompts.

## Code Samples + WebAuthn Options and Responses
```
  const onSubmit = async (event: FormEvent) => {
    event.preventDefault()
    const authenticationOptionsJSON = await getAuthenticationOptionsJSON(email)
    const { challenge } = authenticationOptionsJSON
    const credential = await getCredential(challenge)

    try {
      const authenticationResponse:
      AuthenticationResponseJSON = await
      startAuthentication(
        authenticationOptionsJSON,
      )
    } catch (err) {
      const loginError = err as Error
      setError(loginError.message)
    }

    // then later verifyAuthentication(userCredential, challenge, authenticationResponse)
    // then later router.push('/page-of-auth-content')
  }
```
`console.log(authenticationOptionsJSON)`
<img width="555" alt="image" src="https://github.com/MasterKale/SimpleWebAuthn/assets/57972348/0d125b40-354d-4cfa-ab14-62422e40b3d2">

## Dependencies

- **OS:** macOS 13.5.2 (22G91)
- **Browser:** Version 116.0.5845.187 (Official Build) (arm64)
- **Authenticator:** MacBook TouchID

### SimpleWebAuthn Libraries

```sh
$ npm list --depth=0 | grep @simplewebauthn
├── @simplewebauthn/browser@_._._
├── @simplewebauthn/server@_._._
# ...

@simplewebauthn/browser 7.2.0
@simplewebauthn/server 7.3.1
@simplewebauthn/typescript-types 7.0.0
```

## Additional context

I am using NextJS App Router and have separated my functions to 'use client' for functions to be run in client-side environments and 'use server' for functions to be run in server-side environments

**Comment by MasterKale** [comment] 2023-09-17 19:10
Hello @renchris, unfortunately the code sample you provided doesn't reveal enough about your setup to give me an idea of what might be going wrong. Can you prepare a reproduction repository that I can pull down that includes the simplest NextJS app that can recreate the issue? I can help further when I have something like your setup that I can run locally.

**Comment by renchris** [comment] 2023-09-21 00:50
Hello @MasterKale. Thanks for replying here. Okay, I put my codebase into a public repository which you can pull down [here](https://github.com/renchris/app-router-with-webauthn). I created a README to outline the project files and directories and the steps to run locally.

**Comment by MasterKale** [comment] 2023-09-26 03:47
I think I see the problem, you're making two `navigator.credential.get()` requests. The first is here, when you use `get()` from **@github/webauthn-json**:

https://github.com/renchris/app-router-with-webauthn/blob/main/src/components/LoginPage.tsx#L30-L37

Then you call `startAuthentication()` from @simplewebauthn/browser immediately afterwards:

https://github.com/renchris/app-router-with-webauthn/blob/main/src/components/LoginPage.tsx#L39-L43

Figure out which one you prefer and upgrade your code to use that one exclusively.

It also looks like you're encoding the base64url-encoded credential ID as base64url:

```
Registration credential ID: "kDcVv4FXfuvvi4szvUOM7Nj_WEA"
Authentication allowCredentials entry: "a0RjVnY0RlhmdXZ2aTRzenZVT003TmpfV0VB"
```

The credential ID included in `allowCredentials` needs to be the same credential ID you get back from registration. To confirm that this is the problem, if we base64url-encode the credential ID from registration we'll see it's the same as the credential ID in `allowCredentials` during auth:

```
> Buffer.from('kDcVv4FXfuvvi4szvUOM7Nj_WEA', 'utf-8').toString('base64url')
'a0RjVnY0RlhmdXZ2aTRzenZVT003TmpfV0VB'
```

...this is causing a double-encoding issue, so the credential ID that you include in `allowCredentials` that then gets passed to `startAuthentication()` fails to be recognized by any authenticator. That's why you're only being prompted for security key or hybrid auth in the second call, the one that calls `startAuthentication()` (the first call, to `get()`, shows the credential you expect because no entries are specified in `allowCredentials`, so the browser shows all available credentials.)

Hope that all helps.

As this isn't an issue with SimpleWebAuthn, I'm going to close this issue out. Feel free to re-open if you believe you've identified an actual issue

**Closed by MasterKale** 2023-09-26 03:47 UTC

**Comment by renchris** [comment] 2023-10-18 00:04
Hi Matthew. Thanks, this helped a lot.

I wasn't aware that `get` ' from `@github/webauthn-json'` and `'@simplewebauthn/browser'` from `'@simplewebauthn/browser'` completed the same task of prompting the user for their credentials. I removed the `get` credentials function.

Ah, you're right, I was not decoding my stored encoded credential ID back correctly.

I fixed the `allowsCredentials` to decode back to the exact original `credentialID` Uint8Array value initially provided from `VerifiedRegistrationResponse`  during the user registration step.

```diff
const loginOptionsParameters: GenerateAuthenticationOptionsOpts = {
  timeout: 60000,
  allowCredentials: (usersCredentials as Credential[]).map((userCredential) => ({
-   id: Uint8Array.from(userCredential.externalId, (c) => c.charCodeAt(0)),
+   id: new Uint8Array(Buffer.from(userCredential.externalId, 'base64')),
    type: 'public-key',
  })),
  userVerification: 'required',
  rpID: 'localhost',
}
```

This solved my issue, thank you!
